### ISSUE TITLE
s3fs fails to install on linuxbrew

### ISSUE THREAD

**Issue by ylluminate** [Homebrew/homebrew-fuse#106]
Please note the following:
https://github.com/Linuxbrew/homebrew-core/issues/1818

**Comment by rwhogg** [comment]
Two things worth noting:

* homebrew/fuse is not a supported tap on Linux at this time
* This is very similar to https://github.com/Linuxbrew/brew/issues/214

Note that after https://github.com/Homebrew/brew/pull/1632 is merged, my next intended contribution upstream is to add `libfuse` support to the osxfuse requirement, which should hopefully resolve this issue.

**Comment by ylluminate** [comment]
That's great news. How soon are we looking at to see that merged? Having this method for installing fuse filesystems will certainly be fantastic!

**Comment by MikeMcQuaid** [comment]
> homebrew/fuse is not a supported tap on Linux at this time

Closing due to that.
