### ISSUE TITLE
google drive fuse

### ISSUE THREAD

**Issue by yoshuawuyts** [Homebrew/homebrew-fuse#19]
A quick google yielded 2 popular project, perhaps it'd be cool to include them?
- https://github.com/astrada/google-drive-ocamlfuse
- https://github.com/dsoprea/GDriveFS

Thanks!

**Comment by DomT4** [comment]
They both pass the minimum requirements for inclusion in Homebrew & we'd welcome a PR if anyone wants to submit one.

**Comment by DomT4** [comment]
Closing per the above.
