### ISSUE TITLE
installing encfs on El Capitan fails

### ISSUE THREAD

**Issue by TakiKio** [Homebrew/homebrew-fuse#21]
**this shows up on terminal:**
`main.cpp:591:23: error: assigning to 'int (*)(const char *, const char *, char *, size_t)' from incompatible type 'int (const char *, const char *, char *, size_t, uint32_t)': different number of parameters (4 vs 5)
  encfs_oper.getxattr = encfs_getxattr;
                      ^ ~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [main.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2`

Can anybody help?

**Comment by DomT4** [comment]
Going to need a full `brew gist-logs encfs`.

**Comment by TakiKio** [comment]
Thank you for your answer, but what do I have to do then? Encfs is still not there?

**Comment by DomT4** [comment]
The logs will help us diagnose the problem, and we can help you from that point.

**Comment by TakiKio** [comment]
`Atelier:cellar takikiometzis$ brew reinstall -s encfs
==> Reinstalling homebrew/fuse/encfs
==> Installing dependencies for homebrew/fuse/encfs: makedepend
==> Installing homebrew/fuse/encfs dependency: makedepend
==> Downloading http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.bz2
######################################################################## 100,0%
==> Downloading http://xorg.freedesktop.org/releases/individual/proto/xproto-7.0.25.tar.bz2
######################################################################## 100,0%
==> ./configure --disable-silent-rules --prefix=/private/tmp/makedepend20151123-65781-1vjh99i/makedepend-1.0.5/xproto
==> make install
==> Downloading http://xorg.freedesktop.org/releases/individual/util/util-macros-1.18.0.tar.bz2
######################################################################## 100,0%
==> ./configure --prefix=/private/tmp/makedepend20151123-65781-1vjh99i/makedepend-1.0.5/xorg-macros
==> make install
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/makedepend/1.0.5
==> make install
🍺  /usr/local/Cellar/makedepend/1.0.5: 7 files, 92K, built in 35 seconds
==> Installing homebrew/fuse/encfs
==> Downloading https://github.com/vgough/encfs/archive/v1.8.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/encfs-1.8.1.tar.gz
==> make -f Makefile.dist
==> ./configure --prefix=/usr/local/Cellar/encfs/1.8.1 --with-boost=/usr/local
==> make
Last 15 lines from /Users/takikiometzis/Library/Logs/Homebrew/encfs/03.make:
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D__STDC_FORMAT_MACROS -DRLOG_COMPONENT=encfs -I/usr/local/Cellar/rlog/1.4/include -I/usr/local/Cellar/openssl/1.0.2d_1/include -I/usr/local/include -I../intl -DLOCALEDIR=\"/usr/local/Cellar/encfs/1.8.1/share/locale\" -W -Wall -Wpointer-arith -Wwrite-strings -g -O2 -D_THREAD_SAFE -pthread -c SSL_Cipher.cpp  -fno-common -DPIC -o .libs/SSL_Cipher.o
clang++ -DHAVE_CONFIG_H -I. -I..   -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D__STDC_FORMAT_MACROS -DRLOG_COMPONENT="encfs" -I/usr/local/Cellar/rlog/1.4/include -I/usr/local/Cellar/openssl/1.0.2d_1/include -I/usr/local/include -I../intl -DLOCALEDIR=\"/usr/local/Cellar/encfs/1.8.1/share/locale\" -W -Wall -Wpointer-arith -Wwrite-strings -g -O2 -D_THREAD_SAFE -pthread  -c -o encfsctl.o encfsctl.cpp
clang++ -DHAVE_CONFIG_H -I. -I..   -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D__STDC_FORMAT_MACROS -DRLOG_COMPONENT="encfs" -I/usr/local/Cellar/rlog/1.4/include -I/usr/local/Cellar/openssl/1.0.2d_1/include -I/usr/local/include -I../intl -DLOCALEDIR=\"/usr/local/Cellar/encfs/1.8.1/share/locale\" -W -Wall -Wpointer-arith -Wwrite-strings -g -O2 -D_THREAD_SAFE -pthread  -c -o test.o test.cpp
clang++ -DHAVE_CONFIG_H -I. -I..   -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D__STDC_FORMAT_MACROS -DRLOG_COMPONENT="encfs" -I/usr/local/Cellar/rlog/1.4/include -I/usr/local/Cellar/openssl/1.0.2d_1/include -I/usr/local/include -I../intl -DLOCALEDIR=\"/usr/local/Cellar/encfs/1.8.1/share/locale\" -W -Wall -Wpointer-arith -Wwrite-strings -g -O2 -D_THREAD_SAFE -pthread  -c -o makeKey.o makeKey.cpp
main.cpp:590:23: error: assigning to 'int (*)(const char *, const char *, const char *, size_t, int)' from incompatible type 'int (const char *, const char *, const char *, size_t, int, uint32_t)': different number of parameters (5 vs 6)
  encfs_oper.setxattr = encfs_setxattr;
                      ^ ~~~~~~~~~~~~~~
main.cpp:591:23: error: assigning to 'int (*)(const char *, const char *, char *, size_t)' from incompatible type 'int (const char *, const char *, char *, size_t, uint32_t)': different number of parameters (4 vs 5)
  encfs_oper.getxattr = encfs_getxattr;
                      ^ ~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [main.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-fuse/issues

These open issues may also help:
Encfs https://github.com/Homebrew/homebrew/issues/46254
encfs - no  target `encfs-man.html' - (with cask) yosemite  https://github.com/Homebrew/homebrew/issues/38359
Atelier:cellar takikiometzis$ 
  [23.11.2015, 20:32:30 Wiederhergestellt]
Last login: Mon Nov 23 20:31:52 on console
You have mail.
Atelier:cellar takikiometzis$ brew gist-logs encfs
https://gist.github.com/cdfeea353e0158b4c2d4
Atelier:cellar takikiometzis$ encfs ~/Dropbox/Private.enc/ ~/Private/
-bash: encfs: command not found`

**Comment by herb** [comment]
having the same issue.

[this thread](https://trac.macports.org/ticket/43403#comment:21) on macports claims the same compilation error resulted from multiple installed version of clang and/or boost.

i installed osxfuse via the DMG off the website and NOT using brew. wonder if that's contributing to it. but unclear what to look for to see if the build is pulling in the wrong version. any attempts to guide my fishing would be appreciated.

**Comment by dinomite** [comment]
My error is different

```
$ brew install sshfs
==> Installing sshfs from homebrew/homebrew-fuse
==> Downloading https://github.com/osxfuse/sshfs/archive/osxfuse-sshfs-2.5.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/sshfs-2.5.0.tar.gz
==> Patching
patching file sshfs.c
==> autoreconf --force --install
==> ./configure --prefix=/usr/local/Cellar/sshfs/2.5.0
Last 15 lines from /Users/dinomite/Library/Logs/Homebrew/sshfs/02.configure:
checking for library containing dlsym... none required
checking OpenSSH version... 6.9 >= 4.4, disabling NODELAY workaround
checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SSHFS... no
configure: error: Package requirements (fuse >= 2.3 glib-2.0 gthread-2.0) were not met:

No package 'fuse' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SSHFS_CFLAGS
and SSHFS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

And here's the `brew gist-logs encfs`: https://gist.github.com/anonymous/6a90b08860781fbbd218

**Comment by TakiKio** [comment]
My gist-logs: https://gist.github.com/c900500eef9a1112e192
I still can't find any solution...

**Comment by il-Brando** [comment]
having the same problem.
My gist-logs: https://gist.github.com/e3e2930fde828e36b83e

**Comment by dinomite** [comment]
@DomT4 Is there any other information we can provide that would help?

**Comment by maspotts** [comment]
I have yet another (different) error (also on el capitan: 10.11.2):

==> ./configure --prefix=/opt/brew/Cellar/encfs/1.8.1_1 --with-boost=/opt/brew
==> make
[...]
libtool: link: clang++ -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libencfs.6.dylib  .libs/autosprintf.o .libs/readpassphrase.o .libs/base64.o .libs/ConfigReader.o .libs/ConfigVar.o .libs/Context.o .libs/Cipher.o .libs/CipherKey.o .libs/FileIO.o .libs/RawFileIO.o .libs/BlockFileIO.o .libs/CipherFileIO.o .libs/MACFileIO.o .libs/NameIO.o .libs/StreamNameIO.o .libs/BlockNameIO.o .libs/NullNameIO.o .libs/Interface.o .libs/MemoryPool.o .libs/NullCipher.o .libs/DirNode.o .libs/FileNode.o .libs/FileUtils.o .libs/openssl.o .libs/SSL_Cipher.o   -L/usr/local/lib -L/opt/brew/Cellar/rlog/1.4/lib -lrlog -L/opt/brew/Cellar/openssl/1.0.2e_1/lib -lssl -lcrypto -lboost_serialization-mt /usr/local/lib/libosxfuse_i64.dylib -liconv -lfuse  -g -O2 -pthread   -pthread -install_name  /opt/brew/Cellar/encfs/1.8.1_1/lib/libencfs.6.dylib -compatibility_version 7 -current_version 7.2 -Wl,-single_module
ld: library not found for -lfuse
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libencfs.la] Error 1

**Comment by rlhelinski** [comment]
I am having the same problem now after updating to Brew 7e70d89, a clean bill of `brew doctor` health, and OSXFuse 2.8.2. It started with brew updating and upgrading. I first posted to https://github.com/Homebrew/homebrew/issues/38359 by accident. I can't figure out how to install a previous version of encfs with brew (`versions` seems to be no longer available). I could try an older version of OSXFuse.

$ brew gist-logs encfs
https://gist.github.com/fe5ca11182c1fddf7377

Please help! Thanks

**Comment by maspotts** [comment]
I resolved my issue by removing and then re-installing Caskroom/cask/osxfuse.  After that the upgrade of homebrew/fuse/encfs proceeded normally.  No idea why that worked!

**Comment by rlhelinski** [comment]
@maspotts I tried this and there was no change. I used both brew cask and the System Preferences pane to remove before installing with brew cask and trying to re-build. Same compilation issue.

**Comment by TimJohann** [comment]
You should look if there's a remnant of another installation of osxfuse.  I found there were headers in /usr/local/include/fuse, while Homebrew's osxfuse headers were in /usr/local/include/osxfuse.  I removed the fuse directory in /usr/local/include and the installation succeded.
Hope that helps some of you.

**Comment by rlhelinski** [comment]
@TimJohann that fixed my problem! Thanks! I ruled that out because I thought that brew doctor would check for header files under /usr/local that it didn't put there, but I guess it missed the ones from the manually installed osxfuse.

**Comment by rlhelinski** [comment]
@TimJohann that fixed my problem! Thanks! I ruled that out because I thought that brew doctor would check for header files under /usr/local that it didn't put there, but I guess it missed the ones from the manually installed osxfuse.

**Comment by jgillman** [comment]
@TimJohann @rlhelinski Worked for me too! I honestly don't remember installing osxfuse so I can't remember if I used brew or not.

-----

Just in case others are following along here are the exact steps I took:

1. Open "FUSE for OS X" in System Preferences
1. Click "Remove OSXFUSE" button
1. Go back to System Preferences and right click on "FUSE for OS X" to remove it
1. Install `osxfuse` with brew: `brew cask install osxfuse`
1. Reboot
1. Successfully install `encfs`!!

**Comment by Thinkscape** [comment]
Alternatively, you can just update OSXFuse via the "System Preferences".
That works too...
![image](https://cloud.githubusercontent.com/assets/270528/13374387/b4dbf428-dd83-11e5-9638-cac75f3e401b.png)

**Comment by jgillman** [comment]
@Thinkscape for what it's worth, that did not work for me. I had to completely remove OSXFuse because, even after updating via the System Preferences panel, the error persisted.

Every machine is different though, so who knows what magic may work :stuck_out_tongue:

**Comment by Thinkscape** [comment]
@jgillman have you tried restarting? If you had some process using it in memory, it could've been still using the old version.

**Comment by AFMcGphGL** [comment]
In my case, which is very similar to yours, I had a previous installation of fuse on my machine with left-over files (apparently). I deleted the following:

sudo rm /usr/local/include/fuse.h
sudo rm -rf /usr/local/include/fuse

Then reinstalled encfs using "brew install omebrew/fuse/encfs" 

The installation worked perfectly and I am able to use encfs now on my mac.

Incidentally I had this happen on two of my computers where I had previously installed fuse.

Hope this helps you.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
