### ISSUE TITLE
update s3fs to use osxfuse as dependency

### ISSUE THREAD

**Issue by AlmirKadric** [Homebrew/homebrew-fuse#23]
As I understand fuse4x and osxfuse are being / already have been merged.
We should update https://github.com/Homebrew/homebrew-fuse/blob/master/Formula/s3fs.rb#L18 to use `:osxfuse` instead of `"fuse4x"`

EDIT: after testing, I found that we will also need to bump the project version to 1.79 by updating:
https://github.com/Homebrew/homebrew-fuse/blob/master/Formula/s3fs.rb#L4
https://github.com/Homebrew/homebrew-fuse/blob/master/Formula/s3fs.rb#L5

Reasons for this can be found here:
https://github.com/s3fs-fuse/s3fs-fuse/releases/tag/v1.79
https://github.com/s3fs-fuse/s3fs-fuse/pull/176

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-fuse/commit/cd398442656a21749ad4dad9fb92b1d184e7cf3a.
