### ISSUE TITLE
rofs-filtered failed to build on 10.11.3

### ISSUE THREAD

**Issue by fulldecent** [Homebrew/homebrew-fuse#28]
I am attempting to `brew install rofs-filtered`. This used to work for me in 10.10 but now does not build in 10.11.

`brew doctor` output:

 > Your system is ready to brew.

Build logs are at:

> https://gist.github.com/f4c6dceabd9d03f545e3

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
