### ISSUE TITLE
Installing ifuse fails on OS X 10.11

### ISSUE THREAD

**Issue by dnicolson** [Homebrew/homebrew-fuse#38]
Attempting to run `brew install ifuse` results in the following error:

`osxfuse: Building this formula from source isn't possible due to OS X`

A binary of `osxfuse` is already installed. Is there a workaround?

I was able to install `ifuse` by commenting out the `depends_on` lines in the formulae, is a fix possible?

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
