### ISSUE TITLE
Add XFS fuse support

### ISSUE THREAD

**Issue by kdeldycke** [Homebrew/homebrew-fuse#41]
Just stumble into a project that might be a good addition to this repository.

`fusexfs` is adding XFS support to Fuse for OSX: https://sourceforge.net/projects/fusexfs/

Not sure how I can reuse the `fuse-xfs-0.2.1.dmg` available at: https://sourceforge.net/projects/fusexfs/files/releases/

Shouldn't we build it from source instead?

**Comment by DomT4** [comment]
> Shouldn't we build it from source instead?

Yeah, we'd need that capability for a formula for it to be accepted, although the [Caskroom](https://github.com/caskroom/homebrew-cask) may well take the `.dmg` version.

I can't see any location where upstream have released the source code in an easy-to-use format so you might need to request that from them if you wanted to chase the formula option.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.

**Comment by kdeldycke** [comment]
Just asked the maintainer to produce a source release. See: https://sourceforge.net/p/fusexfs/discussion/general/thread/cb2abcaf/
