### ISSUE TITLE
Question: what is right usage under Yosemite and above

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/homebrew-fuse#47]
Hello,
There is many formulae related to fuse that I like to use on my Mac.
From a certain time `osxfuse` formula is no longer supported on most recent OSX version with this message:
```
brew upgrade osxfuse
==> Upgrading 1 outdated package, with result:
osxfuse 2.8.3
osxfuse: Building this formula from source isn't possible due to OS X
Yosemite and above's strict unsigned kext ban.

You can install with Homebrew Cask:
  brew install Caskroom/cask/osxfuse
```
Then, what is the right solution now to go on using those formulae (`afuse, archivemount, ext4fuse, fuse-zip, ifuse, mp3fs, ntfs-3g, sshfs`...) having `:osxfuse` as dependency:
- is Cask version fullfilling the dependency?
- are the formulae adapted above Yosemite to detect and re-use the system-wide version of osxfuse installed manually from pkg (in /usr/local)?
- other solutions?

Please forgive me if my question is not very clear or clever ;-)

P.S. Maybe is it worth mentioning that my Cellar and Caskroom are not in `/usr/local` but in a dedicated `/opt/homebrew` directory.

**Comment by DomT4** [comment]
Homebrew dependencies starting with `:` are "special" dependencies in some way. They line up with Requirements, in this case `:osxfuse` == [this requirement](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/requirements/osxfuse_requirement.rb), which as you can see can be satisfied in a variety of ways.

Valid ways to meet the dependency:
* The `osxfuse` formula.
* `brew cask install osxfuse`
* Installing the `.pkg` installer from the upstream website.

In that order, pretty much. So yup, you can remove the formula & install via cask or upstream `.pkg` and we'll happily use that. Hope this helps 😃

**Comment by Yann-R** [comment]
Great, very clear! 
Thanks :-)
