### ISSUE TITLE
gcsfuse failed to build in osx 10.10.3

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-fuse#5]
_From @hoozecn on June 10, 2015 9:32_

https://gist.github.com/anonymous/1edb8f0d1efa179d185d

_Copied from original issue: Homebrew/homebrew#40547_

**Comment by DomT4** [comment]
Any idea on this @jacobsa? I can repro here.

**Comment by mistydemeo** [comment]
This appears to have broken with go 1.4.2; I can build gcsfuse with go 1.4 and 1.4.1.

**Comment by DomT4** [comment]
It was only merged into the core [16 days ago](https://github.com/Homebrew/homebrew/pull/40084), after 1.4.2 was merged. As far as I remember the test-bot failure was Yosemite not being able to deal with the `fuse` dep. Still worth kicking this upstream?

**Comment by jacobsa** [comment]
This is a version mismatch; package fuse is being built at or after jacobsa/fuse@8a8429af13902efec4ac6352460b5ce521ac1139, but it looks like gcsfuse is being built before googlecloudplatform@207ebb83a6886b227ca1c2a623ae441d2b9ba8f3.

I'm confused though, because the formula [specifies a particular revision](https://github.com/Homebrew/homebrew-fuse/blob/03879ccbaabe2cb2b0192c809143f5f2a9d2d49c/Formula/gcsfuse.rb#L19) for its dependencies. How is it that you're building from a later one?

**Comment by DomT4** [comment]
Somewhat oddly:

```
brew fetch gcsfuse
brew install gcfuse
```

Works: `🍺  /usr/local/Cellar/gcsfuse/0.1.1: 5 files, 11M, built in 72 seconds`

But:

```
brew install gcsfuse
```

With a clean cache gets:

```
==> go build -o gcsfuse.bin
# github.com/googlecloudplatform/gcsfuse/fs
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:174: cannot use fs (type *fileSystem) as type fuseutil.FileSystem in argument to fuseutil.NewFileSystemServer:
	*fileSystem does not implement fuseutil.FileSystem (wrong type for CreateFile method)
		have CreateFile(*fuseops.CreateFileOp)
		want CreateFile(*fuseops.CreateFileOp) error
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:861: undefined: fuseutil.RespondToOp
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:870: undefined: fuseutil.RespondToOp
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:898: undefined: fuseutil.RespondToOp
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:921: undefined: fuseutil.RespondToOp
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:964: undefined: fuseutil.RespondToOp
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:983: undefined: fuseutil.RespondToOp
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:1036: undefined: fuseutil.RespondToOp
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:1089: undefined: fuseutil.RespondToOp
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:1141: undefined: fuseutil.RespondToOp
src/github.com/googlecloudplatform/gcsfuse/fs/fs.go:1141: too many errors
```

Tested 3 times, Same result as above each time.

**Comment by jacobsa** [comment]
Is it possible that the build environment isn't hermetic, and you're picking up a copy of one of the two packages in your system's Go installation? Or something like that. I wrote the formula just by looking at examples, so maybe I screwed something up with asking for a particular revision and/or configuring the environment?

**Comment by jacobsa** [comment]
Shot in the dark: might this have something to do with the [lack of](https://github.com/Homebrew/homebrew-fuse/blob/03879ccbaabe2cb2b0192c809143f5f2a9d2d49c/Formula/gcsfuse.rb#L24) `:using => :git` on some dependencies, compared to others [that do have it](https://github.com/Homebrew/homebrew-fuse/blob/03879ccbaabe2cb2b0192c809143f5f2a9d2d49c/Formula/gcsfuse.rb#L44)?

I don't know Ruby and could find no documentation on `go_resource` (I auto-generated the list of dependencies using [homebrew-go-resources](https://github.com/samertm/homebrew-go-resources)), so I'm not equipped to say.

**Comment by DomT4** [comment]
Is this still reproducing for everyone with the latest version? I can't seem to get it to happen again locally now.

**Comment by mistydemeo** [comment]
Works for me too ¯\_(ツ)_/¯

**Comment by DomT4** [comment]
> Shot in the dark: might this have something to do with the lack of :using => :git

Our preference is to use `.git` URLs rather than `:using => :git` but neither method should impact how they are fetched.

> Works for me too ¯_(ツ)_/¯

Cool, Thanks Misty. Maybe it was a race of some sort :confused:. Closing here presuming resolved. Thanks all.
