### ISSUE TITLE
[sshfs][osxfuse]An unsatisfied requirement failed this build.

### ISSUE THREAD

**Issue by rprimus** [Homebrew/homebrew-fuse#57]
Thu Aug 11 08:12:49 BST 2016

This is failing to upgrade/install:
```
rprimus@mbp /usr/local/src % brew upgrade --all
==> Upgrading 2 outdated packages, with result:
homebrew/fuse/sshfs 2.8, youtube-dl 2016.08.10
sshfs: OsxfuseRequirement unsatisfied!

You can install with Homebrew Cask:
  brew cask install osxfuse

You can download from:
  https://osxfuse.github.io/
Error: An unsatisfied requirement failed this build.
```

```
 % brew info osxfuse
Error: No available formula with the name "osxfuse"
```

It appears that the ```osxfuse``` homebrew formula has been removed in favour of using the cask (due to recent duplication homebrew/cask cleanup).

Is there a way to have a cask as a dependency?

**Comment by rprimus** [comment]
Thu Aug 11 08:43:39 BST 2016

P.S.   The following formulae all depend on ```osxfuse```:

```
% ag -il osxfuse
afuse.rb
archivemount.rb
avfs.rb
bindfs.rb
btfs.rb
djmount.rb
encfs.rb
ext2fuse.rb
ext4fuse.rb
fuse-zip.rb
fuse4x.rb
gcsfuse.rb
gitfs.rb
ifuse.rb
mp3fs.rb
ntfs-3g.rb
ori.rb
rofs-filtered.rb
s3-backer.rb
s3fs.rb
securefs.rb
simple-mtpfs.rb
sshfs.rb
tup.rb
wdfs.rb
xmount.rb
```

**Comment by ilovezfs** [comment]
The formula have the requirement `:osxfuse` not the dependency `"osxfuse"` and the Cask can satisfy the `:osxfuse` requirement: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/requirements/osxfuse_requirement.rb#L5

**Comment by rprimus** [comment]
Thu Aug 11 09:12:26 BST 2016

@ilovezfs Ahhhhh!!!  Thanks for the clarification.  Had only seen the ```depends on:``` in the formula (and also not fully scrutinised the error message).

Closing.

**Comment by rprimus** [comment]
Thu Aug 11 09:17:24 BST 2016

Message should read:
```
Error: An unsatisfied requirement was no met.
```

as there was no attempt to install ('build') the cask.
