### ISSUE TITLE
[gitfs] ffi.h not found

### ISSUE THREAD

**Issue by whcordis** [Homebrew/homebrew-fuse#63]
I'm having a persistent issue building gitfs with it's root cause being that the compile isn't detecting libffi even thought it's available in MacOSX and installed via homebrew

libffi: stable 3.0.13 (bottled), HEAD [keg-only]
Portable Foreign Function Interface library
https://sourceware.org/libffi/
/usr/local/Cellar/libffi/3.0.13 (15 files, 377.1K)
  Built from source on 2014-10-16 at 23:09:13
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libffi.rb

GIST: https://gist.github.com/whcordis/7cbb441295c297bcc3c2249da48de965

**Comment by umireon** [comment]
gitfs is supposed to be linked with macOS's libffi since libffi is keg-only and not specified as the dependency of gitfs.
Therefore, Homebrew's libffi have nothing with this issue.

Do you have `ffi.h` in `/usr/include/ffi/` or `/usr/include/libffi`?
You can check that by running:

```
$ ls /usr/include/ffi /usr/include/libffi
ls: /usr/include/libffi: No such file or directory
/usr/include/ffi:
ffi.h		fficonfig.h	ppc-darwin.h	x86-ffitarget.h
ffi_common.h	ffitarget.h	ppc-ffitarget.h
```

**Comment by ilovezfs** [comment]
New version has shipped. Please try again.
