### ISSUE TITLE
Are encfs deps correct?

### ISSUE THREAD

**Issue by mirfilip** [Homebrew/homebrew-fuse#82]
Looking at [encFs 1.9 deps](https://github.com/vgough/encfs/blob/v1.9/INSTALL.md#dependencies) and comparing them with [newest formula](https://github.com/Homebrew/homebrew-fuse/blob/master/Formula/encfs.rb), they are different.

1. It seems [boost is not a dependency anymore](https://github.com/vgough/encfs/blob/v1.9.1/ChangeLog#L42). I'm not 100% sure about that as it still checks some boost-related flags but it seems it had been dropped by `1.9-rc1`
2. `intl` is not listed as a dep in formula

Boost seems to be a biggest drag as it's huge (+400MB).

I'm fine with fixing that, just need a confirmation.

**Comment by umireon** [comment]
`intl` is included in `gettext` and thus unnecessary in deps list.
As for boost, I totally agree with you 👍

**Comment by mirfilip** [comment]
@umireon That means `intl` is a transitive dependency for `encfs`. Still, [encfs guys list it](https://github.com/vgough/encfs/blob/v1.9/INSTALL.md#dependencies) as a main dependency alongside `gettext` and that formula should stick to that.

At least that's what I've seen in other formulas I checked.

**Comment by umireon** [comment]
@mirfilip Good point 👍, I see encfs DO depends on libintl.
However, `depends_on` stanza of a Formula is the place to declare what **Formula** is needed to use it.
Since there is [no `libintl` Formula](http://brewformulas.org/search?utf8=✓&search%5Bterm%5D=libintl&commit=Search), `depends_on "intl"` is but illegal in the Homebrew land.

**Comment by MikeMcQuaid** [comment]
This seems to be working now regardless.

**Comment by mirfilip** [comment]
I never stated it didn't work. This was one of optimization tasks, so that huge Boost lib is not downloaded.

**Comment by MikeMcQuaid** [comment]
@mirfilip Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!
