### ISSUE TITLE
encfs dependency fails to detect osxfuse

### ISSUE THREAD

**Issue by nilbus** [Homebrew/homebrew-fuse#83]
- [x] Ran `brew update`; on rev 82aace9 from Nov 12, 2016
- [x] Ran `brew doctor`; nothing looks relevant or serious ([output][1])

[1]: https://gist.github.com/nilbus/ffd80cb3b00975354137aeaf00ff90a1

I'm on an old encfs, trying to upgrade. When I try, it claims osxfuse is not installed, although I have installed both via cask and by downloading the linked installer.

```
nilbus@hydra ~ $ brew upgrade encfs
==> Upgrading 1 outdated package, with result:
homebrew/fuse/encfs 1.9
encfs: OsxfuseRequirement unsatisfied!

You can install with Homebrew-Cask:
  brew cask install osxfuse

You can download from:
  https://osxfuse.github.io/
Error: An unsatisfied requirement failed this build.


nilbus@hydra ~ $ brew cask install osxfuse
Warning: A Cask for osxfuse is already installed.

To re-install osxfuse, run:
  brew cask reinstall osxfuse


nilbus@hydra ~ $ brew upgrade encfs
==> Upgrading 1 outdated package, with result:
homebrew/fuse/encfs 1.9
encfs: OsxfuseRequirement unsatisfied!

You can install with Homebrew-Cask:
  brew cask install osxfuse

You can download from:
  https://osxfuse.github.io/
Error: An unsatisfied requirement failed this build.
```

**Comment by nilbus** [comment]
Happy to provide more info as needed.

**Comment by umireon** [comment]
@nilbus Can you `brew cask reinstall osxfuse` or `brew uninstall --force osxfuse; brew cask uninstall --force osxfuse; brew cask install osxfuse`, then try `brew upgrade encfs`.
Your osxfuse installation seems to be broken.

**Comment by nilbus** [comment]
Reinstalling osxfuse did the trick. Thanks!
